"""initial_schema

Revision ID: 10cf88b737b1
Revises: 
Create Date: 2026-05-28 15:53:20.114186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cf88b737b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('liquidity_tier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocation', sa.JSON(), nullable=False),
    sa.Column('liquidity', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('crypto_holdings',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('coingecko_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('fixed_income_holdings',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('compounding_frequency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('mutual_fund_holdings',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('scheme_code', sa.String(), nullable=False),
    sa.Column('units', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('nav_at_purchase', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('monthly_sip', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('units', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_history')
    op.drop_table('transactions')
    op.drop_table('mutual_fund_holdings')
    op.drop_table('fixed_income_holdings')
    op.drop_table('crypto_holdings')
    op.drop_table('portfolio_snapshots')
    op.drop_table('assets')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
