"""add price_per_unit to valuation_history

Revision ID: ae2fc64ac52f
Revises: a6c964d55107
Create Date: 2026-06-09 10:26:55.324671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2fc64ac52f'
down_revision: Union[str, Sequence[str], None] = 'a6c964d55107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valuation_history', sa.Column('price_per_unit', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valuation_history', 'price_per_unit')
    # ### end Alembic commands ###
