"""holding uniqueness constraints for atomic asset merge (A10b)

Revision ID: f448b186cdf1
Revises: 509c02fff358
Create Date: 2026-06-05 16:25:39.852468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f448b186cdf1'
down_revision: Union[str, Sequence[str], None] = '509c02fff358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_crypto_holdings_user_coingecko', 'crypto_holdings', ['user_id', 'coingecko_id'])
    op.create_unique_constraint('uq_mf_holdings_user_scheme', 'mutual_fund_holdings', ['user_id', 'scheme_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mf_holdings_user_scheme', 'mutual_fund_holdings', type_='unique')
    op.drop_constraint('uq_crypto_holdings_user_coingecko', 'crypto_holdings', type_='unique')
    # ### end Alembic commands ###
